# Generated by Django 4.2 on 2023-04-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_toy_alter_feeding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='toy',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
