# Generated by Django 4.2 on 2023-04-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_cat_toy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='toy',
            new_name='toys',
        ),
    ]
